// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyranyxlcdcqcaeooski.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cmFueXhsY2RjcWNhZW9vc2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzk1MjUsImV4cCI6MjA1MDg1NTUyNX0.poCk4RBVdJguKXB2B3X5Ss9Qw8qTjw5TrR9X0LcHRLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);